"""
This type stub file was generated by pyright.
"""

import torch
from modulefinder import Module
from . import extension
from torchvision import _autograd_registrations, _meta_registrations, datasets, io, models, ops, transforms, utils
from .version import __version__

_image_backend = ...
_video_backend = ...
def set_image_backend(backend): # -> None:
    """
    Specifies the package used to load images.

    Args:
        backend (string): Name of the image backend. one of {'PIL', 'accimage'}.
            The :mod:`accimage` package uses the Intel IPP library. It is
            generally faster than PIL, but does not support as many operations.
    """
    ...

def get_image_backend(): # -> str:
    """
    Gets the name of the package used to load images
    """
    ...

def set_video_backend(backend): # -> None:
    """
    Specifies the package used to decode videos.

    Args:
        backend (string): Name of the video backend. Only 'pyav' is supported.
            The :mod:`pyav` package uses the 3rd party PyAv library. It is a Pythonic
            binding for the FFmpeg libraries.
    """
    ...

def get_video_backend(): # -> str:
    """
    Returns the currently active video backend used to decode videos.

    Returns:
        str: Name of the video backend. Currently only 'pyav' is supported.
    """
    ...

def disable_beta_transforms_warning(): # -> None:
    ...

